from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.google.com/")
    page.get_by_label("Pesquisar", exact=True).click()
    page.get_by_label("Pesquisar", exact=True).fill("gay furry porn")
    page.get_by_role("link", name="Imagens").click()
    page.get_by_role("button", name="ANDAR 19, Animação Furry Gay").click()
    with page.expect_popup() as page1_info:
        page.get_by_role("link", name="ANDAR 19, Animação Furry Gay", exact=True).click()
    page1 = page1_info.value
    page1.get_by_role("button", name="Tenho 18 anos ou mais - Entrar").click()
    page1.locator(".mgp_playbackBg").click()
    page2 = context.new_page()
    page2.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page3 = context.new_page()
    page3.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page4 = context.new_page()
    page4.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page5 = context.new_page()
    page5.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page6 = context.new_page()
    page6.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page7 = context.new_page()
    page7.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page8 = context.new_page()
    page8.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page9 = context.new_page()
    page9.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page10 = context.new_page()
    page10.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page11 = context.new_page()
    page11.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page12 = context.new_page()
    page12.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page13 = context.new_page()
    page13.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page14 = context.new_page()
    page14.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page15 = context.new_page()
    page15.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page16 = context.new_page()
    page16.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page17 = context.new_page()
    page17.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page18 = context.new_page()
    page18.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page19 = context.new_page()
    page19.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page20 = context.new_page()
    page20.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page21 = context.new_page()
    page21.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page22 = context.new_page()
    page22.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page23 = context.new_page()
    page23.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page24 = context.new_page()
    page24.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page25 = context.new_page()
    page25.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page26 = context.new_page()
    page26.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page27 = context.new_page()
    page27.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page28 = context.new_page()
    page28.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page29 = context.new_page()
    page29.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page30 = context.new_page()
    page30.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page31 = context.new_page()
    page31.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page32 = context.new_page()
    page32.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page33 = context.new_page()
    page33.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page34 = context.new_page()
    page34.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page35 = context.new_page()
    page35.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page36 = context.new_page()
    page36.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")
    page37 = context.new_page()
    page37.goto("https://pt.pornhub.com/view_video.php?viewkey=641e6b82a8dd1")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
